---
title: "chapter5_回帰分析の基礎"
format: gfm
editor: visual
---

## 前準備

```{r}
library(tidyverse)
library(patchwork)
```

## 数値例で理解する最小二乗法

```{r}
data <- tribble(
  ~y1, ~x1,
  40, 5,
  20, 1,
  50, 3,
  10, 2,
)
```

```{r}
data |>
  ggplot(aes(x = x1, y = y1)) +
  geom_point(size = 3, shape = 21) +
  geom_abline(slope = 6.857, intercept = 11.143) +
  geom_abline(slope = 10.909, intercept = 0000, linetype = "dashed")
```

```{r}
yhat1 <- data |>
  pull(x1) |>
  map_dbl(~ 11.143 + 6.857 * .)

e1 <- data |>
  pull(y1) - yhat1

print(yhat1)
print(e1)
```

```{r}
yhat2 <- data |>
  pull(x1) |>
  map_dbl(~ 10.909 * .)

e2 <- data |>
  pull(y1) - yhat2

print(yhat2)
print(e2)
```

```{r}
print(sum(e1))
print(sum(e2))
```

```{r}
e1b <- e1^2
e2b <- e2^2
print(sum(e1b))
print(sum(e2b))
```

## 種明かし：最小二乗法による切片と傾きの公式

$$
\hat{\beta}_0 = \bar{Y} - \hat{\beta}_1\bar{X} \\
\hat{\beta}_1 = \frac{\sum{(X_i - \bar{X})(Y_i - \bar{Y})}}{\sum{(X_i - \bar{X})^2}}
$$

```{r}
xbar <- data |> pull(x1) |> mean()
ybar <- data |> pull(y1) |> mean()

print(xbar)
print(ybar)
```

```{r}
hensax <- data |> pull(x1) |> map_dbl(~ . - xbar)
hensay <- data |> pull(y1) |> map_dbl(~ . - ybar)

print(hensax)
print(hensay)
```

```{r}
hensaxy <- hensax * hensay
numerator <- sum(hensaxy)

print(numerator)
```

```{r}
hensax2 <- hensax^2
denominator <- sum(hensax2)

print(denominator)
```

```{r}
b1 <- numerator / denominator
b0 <- ybar - b1 * xbar

print(b1)
print(b0)
```

```{r}
model1 <- data |> lm(data = _, y1 ~ x1)
summary(model1)
```

## 条件付き期待値としての回帰モデル

```{r}
data <- tribble(
  ~y1, ~x1,
  1, 1,
  2, 1,
  3, 1,
  4, 2,
  5, 2,
  6, 2,
  7, 3,
  8, 3,
  9, 3,
)

print(data |> pull(y1) |> mean())
```

```{r}
model2 <- data |>
  lm(data = _, y1 ~ x1)

summary(model2)
```

```{r}
p1 <- data |>
  ggplot(aes(x = x1, y = y1)) +
  geom_point(size = 3, shape = 21) +
  labs(
    title = "散布図"
  ) +
  theme(
    text = element_text(family = "Hiragino Sans")
  )

p2 <- data |>
  ggplot(aes(x = x1, y = y1)) +
  geom_point(size = 3, shape = 21) +
  geom_smooth(method = "lm", se = FALSE, color = "black", size = 0.5) +
  labs(
    title = "E[Y|X]"
  ) +
  theme(
    text = element_text(family = "Hiragino Sans")
  )

p1 + p2
```

## 最小二乗法による切片と傾きの公式（補遺）

```{r}
data <- tribble(
  ~x1, ~y1,
  5, 40,
  1, 20,
  3, 50,
  2, 10,
)
data
```

```{r}
model3 <- data |>
  lm(data = _, y1 ~ x1)

bOLS <- summary(model3)$coefficient[2, 1]
ussOLS <- sum((resid(model3))^2)
```

```{r}
b1 <- NULL
uss <- NULL
set.seed(1)
for(i in 1:10000) {
  a1 <- 11.14286
  b1[i] <- runif(1, -10, 25)
  yhat <- a1 + b1[i] * data$x1
  uss[i] <- sum((data$y1 -yhat)^2)
}

print(summary(uss))
print(ussOLS)
```

```{r}
result_df <- tibble(b1 = b1, uss = uss)

ggplot(data = result_df, aes(x = b1, y = uss)) +
  geom_point(size = 0.1) +
  geom_vline(xintercept = bOLS, linetype = "dashed") +
  geom_hline(yintercept = ussOLS)
```
